CREATE TABLE PasswordResetTokens (
    TokenID BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserID BIGINT NOT NULL,
    Token VARCHAR(255) NOT NULL UNIQUE,
    ExpiryDate DATETIME NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
